name: CycleGANMonet
channels:
  - conda-forge
  - defaults
  - pytorch
  - anaconda
dependencies:
  - python=3.9
  - codecov
  - matplotlib
  - kaggle
  - flake8
  - pre-commit
  - sagemaker-python-sdk
  - numpy
  - pandas
  - natsort
  - pillow
  - scipy
  - ipython
  - tensorflow
  - ipywidgets
  - jupyter
  - boto3
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
