name: DeepRL
channels:
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python=3.10
  - gym
  - jupyter
  - jupyterlab
  - matplotlib-base
  - seaborn
  - hyperopt
  - pyglet
  - numpy
  - pytorch
  - torchvision
  - torchaudio
