name: DeepRL
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - gym
  - hyperopt
  - jupyter
  - jupyterlab
  - matplotlib-base
  - numpy
  - pip
  - pybox2d
  - pyglet
  - python=3.10
  - pytorch
  - seaborn
  - torchaudio
  - torchvision
